apiVersion: "v1"
kind: ConfigMap
metadata:
  name: video
  labels:
    app: video
data:
  # 服务配置
  server_name: video-server

  # mysql 配置
  db_host: docker.for.mac.host.internal
  db_port: "3306"
  db_user: root
  db_password: root
  db_database: qvbilam_video

  # redis 配置
  redis_host: docker.for.mac.host.internal
  redis_port: "6379"
  redis_password: ""
  redis_database: "0"

  # es 配置
  es_host: docker.for.mac.host.internal
  es_port: "9200"

  # 用户服务配置
  user-server_host: docker.for.mac.host.internal
  user-server_port: "9801"
  user-server_name: user-server
