apiVersion: v1
kind: Service
metadata:
  name: video-server
spec:
  selector:
    app: video-server
  ports:
    - name: grpc-video-server
      protocol: TCP
      port: 9802
      targetPort: 9501
  type: LoadBalancer